[ci] Scan files for non-ASCII characters

diff --git a/.github/workflows/format.yml b/.github/workflows/format.yml
--- a/.github/workflows/format.yml
+++ b/.github/workflows/format.yml
@@ -12,6 +12,19 @@ on:
     types: [opened, synchronize, reopened]
 
 jobs:
+  ascii-encoding:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v5
+
+      - name: Scan files for non-ASCII characters
+        run: |
+          if grep -rnP '[^\x00-\x7F]' --exclude-dir=.git .; then
+            echo "error: non-ASCII characters found."
+            exit 1
+          fi
+
   clang-format:
     runs-on: ubuntu-latest
 
